.dockerignore, .github/workflows/build-deploy.yml, Dockerfile, next.config.mjs
this adds a dockerfile and github actions workflow to deploy to the acdh-ch cluster on every push to the main branch,
=> build: add github action to deploy to acdh-ch cluster

src/pages/person/[id].page.tsx
this dumps the full person object on the details page.
=> feat: dump payload on entitiy details page

package-lock.json, package.json, src/features/common/entity.model.ts, src/features/geomap/MaplibreMap.tsx, src/features/geomap/maplibremap.module.css, src/features/layouts/PageLayout.tsx, src/mocks/db.ts, src/mocks/intavia-api.mocks.ts, src/pages/geomap.page.tsx
Simple GeoMap Page with Map Component (react-map-gl) and markers
=> add geomap page

package-lock.json, src/features/common/entities.slice.ts, src/features/common/intavia-api.service.ts, src/features/visual-querying/ConstraintList.tsx, src/features/visual-querying/DateConstraintView.tsx, src/features/visual-querying/Histogram.tsx, src/features/visual-querying/PersonShape.tsx, src/features/visual-querying/RingConstraint.tsx, src/features/visual-querying/TextConstraintView.tsx, src/features/visual-querying/VisualQuerying.tsx, src/features/visual-querying/visual-querying.module.css, src/features/visual-querying/visualQuerying.slice.ts, src/mocks/db.ts, src/mocks/intavia-api.mocks.ts
- extend mocking with statistics endoint and parameter search
- add name and date of death constraints to visual query
- connect visual query widgets with mock data
- connect visual query with mock param search endpoint
=> Add vis query mock api

src/features/storycreator/StoryFlow.tsx, src/features/storycreator/StoryMap.tsx, src/features/storycreator/StoryTextCreator.tsx, src/features/storycreator/storycreator.slice.ts
Added types to StoryTextCreator, StoryMap and StoryFlow
=> chore: add-types-to-storytextcreator-storymap-storyflow

src/features/common/entities.slice.ts, src/features/common/intavia-api.service.ts, src/features/visual-querying/VisualQuerying.tsx, src/mocks/db.ts, src/mocks/intavia-api.mocks.ts
this integrates the `getPersonsByParam` endpoint into `getPersons`.
x-ref: https://github.com/InTaVia/web/pull/28#issuecomment-1123974090
=> refactor: integrate getPersonsByParam endpoint in getPersons

src/features/excel-upload/ExcelUpload.tsx, src/features/geomap/MaplibreMap.tsx, src/features/storycreator/SlideEditor.tsx, src/features/storycreator/StoryGUICreator.tsx, src/features/storycreator/StoryMap.tsx, src/features/storycreator/StoryMapPin.tsx, src/features/storycreator/storycreator.slice.ts
- Added a reference to the map, so that we are able to use the map somewhere else
- Added points to the StoryMap
- Fit bounds (in the StoryMap, using the mapRef) to the points inside the map
=> Update map for storycreator

package-lock.json, package.json, src/features/common/entities.slice.ts, src/features/common/store.ts, src/pages/_app.page.tsx
this pr adds `redux-persist` to persist the `entities` redux state slice to `localStorage`.
=> feat: persist entities slice to localstorage

package-lock.json, package.json, src/pages/_app.page.tsx, tailwind.config.cjs, tsconfig.json
Adds tailwindcss and headlessui to the project.
Plan: use tailwindcss/headlessui for new components and gradually get rid of mui.
=> feat: add tailwindcss and headlessui

package.json, src/features/layouts/page-layout.tsx, src/features/ui/toast.tsx, src/pages/ui-test.page.tsx
add toast UI component/function
=> Feat/styled UI components v2

src/features/common/visualization.slice.ts, src/features/ego-network/ego-network-component.tsx, src/features/ego-network/use-nodes-and-links.ts, src/features/entities/cultural-heritage-object-details.tsx, src/features/entities/group-details.tsx, src/features/entities/historical-event-details.tsx, src/features/entities/person-details.tsx, src/features/entities/place-details.tsx, src/features/visualization-layouts/visualization.tsx, src/features/visualization-wizard/visualization-wizard.tsx
=> Add ego-network to VAS

src/components/search/edit-entity-dialog.tsx, src/components/search/search-page-footer.tsx
also, paginate long lists of entity relations in edit forms
=> fix: edit form for local entities

src/features/ego-network/network-component.tsx, src/features/ego-network/use-nodes-and-links.ts
Network-component now shows loading indicator until all events and related entities have been fetched.
=> Fix network rendering before all entities are fetched

src/features/data-import/load-data.tsx
Add idm-json import for WP4 hackathon
This functionality should be migrated to the data-import module later on.
=> Add idm-json import

src/app/i18n/common/en.ts, src/app/i18n/common/index.ts, src/components/search/search-facets.tsx, src/components/search/search-form.tsx
- Rename "more" button -> "advanced search"
- Move "clear" button
- Clear button now clears all search fields
See #188
=> Refactor search form buttons

src/components/search/collection-view.tsx, src/components/search/search-result.tsx
- whole list cell is clickable as link
- change cell bg on hover
- underline label on hover
=> feat: improve links in search-result-list and collection-view

src/components/search/collection-view.tsx, src/components/search/search-result.tsx
- Stop propagation from onClick events from menu items to NextLink
- Fix underlining of labels on hover
=> fix: selecting menu item no longer opens link to detail page

src/components/search/collection-toolbar.tsx, src/components/search/collection-view.tsx, src/components/search/search-form.tsx, src/components/search/search-page-footer.tsx, src/components/search/search-result.tsx, src/components/search/search-results-toolbar.tsx, src/components/search/search-results-view.tsx
Motivation: Make more entities fit on screen
=> feat: search page reduce paddings

package-lock.json, package.json, src/app/i18n/common/en.ts, src/app/i18n/common/index.ts, src/components/search/collection-toolbar.tsx, src/components/search/collection-view.tsx, src/components/search/delete-collection-alert.tsx, src/components/search/search-results-toolbar.tsx, src/features/data-panel/data-panel.tsx, src/features/data-panel/entity-item.tsx, src/features/data-panel/event-item.tsx, src/features/data-panel/group-item.tsx, src/features/data-panel/visualized-panel.tsx, src/features/entities/entity-relations.tsx, src/features/storycreator/StoryOverview.tsx, src/features/storycreator/delete-story-alert.tsx, src/features/storycreator/story-creator-toolbar.tsx, src/features/ui/AllotmentHeader.tsx, src/features/ui/analyse-page-toolbar/PaneToggle.tsx, src/features/ui/analyse-page-toolbar/toolbar.tsx, src/features/visualization-layouts/workspaces.tsx, src/styles/index.css
- adjustments to button styles
- consistent list hover styles
- consistent toolbar styles
- new pane toggle icons
- confirm deletion of story in delete-story-alert dialog
=> Consistent list and toolbar styles

src/features/ui/analyse-page-toolbar/layout-popover.tsx, src/features/visualization-layouts/visualization-group.tsx
two columns top, one large bottom
two columns bottom, one large top
=> added 2 additiona 3 panel layouts

src/app/i18n/common/en.ts, src/app/i18n/common/index.ts, src/features/common/visualization.slice.ts, src/features/geo-map/geo-map.config.ts, src/features/storycreator/storycreator.slice.ts, src/features/visualization-layouts/workspaces.slice.ts, src/features/visualization-wizard/delete-visualization-alert.tsx, src/features/visualization-wizard/visualization-select.tsx, src/features/visualization-wizard/visualization-wizard.tsx
Visualization Wizard (VAS and SC context aware):
- Visualization Icons
- Dropdown with sorting / sections
- Clone Visualizations (copy; original id extended)
- Transform Type of Visualization (create new and copy data)
TODO:
- Transform Visualization Type: also transform visualization properties (e.g. time coloring, etc.)
=> visualization-wizard-v2

package.json, src/components/search/collection-view.tsx, src/components/search/search-result.tsx, src/features/common/quality-indicators.tsx, src/features/entities/entity-details.tsx, src/features/entities/entity-edit-form-fields.tsx, src/features/entities/entity-relations.tsx
added qual inidcators: search & collection list
added no date indicators tor: detail list & edit page
added links to related entities in event-list of detail view
=> added quality indicators
